theme: jekyll-theme-minimal
title: Hao Wang
description: Welcome to Hao Wang's Homepage
# logo: /assets/img/me.jpg
description: PhD Student <br> Hefei University of Technology. 
show_downloads: false
google_analytics: UA-173010224-1
