title: Hao Wang
description: Welcome to Hao Wang's Homepage
url: "https://waynehfut.com"
google_analytics: UA-173010224-1
remote_theme: ankitsultana/researcher@gem
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/waynehfut"
footer_text: "This is Hao Wang's homepage. Please feel free to contact me via the mail for any question."

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Meet"
    link: "https://meet.waynehfut.com"
  - name: "Contact"
    link: "contact"
